### PR TITLE
Fix plotting functionality

### PR DESCRIPTION
**Pull request by rayosborn**
This fixes some issues in using interactive and non-interactive mode (plt.ion or plt.ioff), plotting within an IPython qtconsole that uses PyQt5 as the backend, and plotting from parent NXentry or NXroot groups.

### CODE REVIEW

**Comment by tacaswell** [comment]
You really should avoid using `pyplot` programtically....

**Comment by rayosborn** [comment]
We don't use it in the main NeXpy code; this is just a convenience function to provide plots within an interactive session. It is not going to be embedded in a larger framework. I'm open to modifying it if you think it will cause other problems but it does what it is designed to do. Is pyplot being deprecated?

**Comment by tacaswell** [comment]
pyplot holds the global state of the 'current figure' which can change
unexpectedly (ex, when the user clicks on a figure) which may lead to
unexpected behavior.

**Comment by rayosborn** [comment]
I don't think that's a problem here. The plot module is only provided so that someone can call "nexus_data.plot()" in an interactive session, much like they would use plt.plot. It's not meant to be used in a program.

**Pull request merged**
